config/routes.rb
Rails.application.routes.draw do
  root to: 'teachers#index'
  devise_for :users
  resources :teachers
  get '/student_view', to: 'users#student_view', as: 'student_view'
  get '/teacher_view', to: 'users#teacher_view', as: 'teacher_view'
  get "/payments/session", to: "payments#get_stripe_id"
  get "/payments/success", to: "payments#success"
  post "/payments/webhooks", to: "payments#webhooks"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :teacher
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :teachers_styles, dependent: :delete_all
    has_many :teachers, through: :teachers_styles
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :teachers_styles, dependent: :delete_all
  has_many :styles, through: :teachers_styles
  has_one_attached :picture

  #  Validations for availability attribute
  validates :availability, presence: true, length: { in: 1...300 }

  # Validations for price attribute
  validates :price, presence: true, length: { in: 1...300 }, numericality: { only_integer: true }

  # Validations for lesson_length attribute
  validates :lesson_length, numericality: { only_integer: true }
  
  # Validations for bio attribute
  validates :bio, :teaching_info, presence: true, length: { in: 1...4000 }
  
  # Validations for picture attribute
  validates :picture, presence: true

end

app/models/teachers_style.rb
class TeachersStyle < ApplicationRecord
  belongs_to :teacher
  belongs_to :style

  # Validation for speciality attribute to exist
  validates :teacher_id, :style_id, presence: true
  validates_uniqueness_of :speciality , conditions: -> { where(speciality: true) }, scope: :teacher_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :teacher, dependent: :destroy
  has_many :bookings

  # Validates Full Name for user sign-up
  validates :fullname, presence: true, length: { in: 1...150 }

  # Validates email for User sign-up
  validates :email, presence: true, uniqueness: { case_sensitive: true }, length: { in: 1...75 }

  # Validates password for user sign-up
  validates :password, confirmation: true, presence: true, length: { in: 1...50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    # Used for Devise
    def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:fullname, :email, :password, :password_confirmation)}

          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:fullname, :email, :password, :current_password, :password_confirmation)}
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_profile, only: [:show, :edit, :update, :destroy]

  def index
    # checks whether params is defined. If so, it runs filtering method. If not, loads all teacher profiles
    if defined? params[:style][:name]
      @teachers = filter_teacher_profiles_by_style(params[:style][:name])
    else
      @teachers = Teacher.all
    end

    # Loads all Styles for filtering form
    @style = Style.new
   
  end

  # Method used for filtering Teacher profiles by style
  def filter_teacher_profiles_by_style(styles)
    Teacher.where(id: TeachersStyle.where(style_id: styles).map{|x| x.teacher_id}.uniq)
  end

  # Show a single profile
  def show
  end

  # Sets up the form for Profile creation. A new teacher object is created and all styles loaded into the instance variable.
  def new
    @teacher = Teacher.new
    @styles = Style.all
  end

  # Create a new Teacher Profile
  def create

      # Teacher Profile creation
      @teacher = Teacher.new(profile_params)
      @teacher.user_id = current_user.id
      @teacher.save

    if @teacher.save

      # Adds a style with the speciality marked as true in teachers_styles join table
      add_speciality_style(params[:teacher][:speciality])

      # Adds all other styles to the profile
      add_other_styles(params[:teacher][:styles])

      flash[:notice] = "Teacher profile created successfully"

      redirect_to teacher_path(current_user.teacher.id)

    else
      render 'new'
    end
  end

  # used for adding the speciality style to the Teachers Profile. Searches then adds the style. Changes the speciality attribute in the Teachers_style join table to 'true'.
  def add_speciality_style(style)
    speciality = Style.find(style)
    current_user.teacher.styles << speciality
    current_user.teacher.teachers_styles.first.update(speciality: true)
  end

  # Checks whether a a checkbox is ticket first. If so it searches and adds each style to the Teacher Profile. If no checkboxes are ticked, 'other styles' is left blank.
  def add_other_styles(styles)
    if styles.present?
      if styles.kind_of?(Array)
        styles.each do |style|
          found_style = Style.find(style)
          current_user.teacher.styles << found_style
        end
      else
        found_style = Style.find(styles)
        current_user.teacher.styles << found_style
      end
    end
  end

  # Edit a single Teacher Profile
  def edit
  end

  # Updating a Teacher Profile
  def update
  
    # Updates all the attributes in Teacher Table of the Profile
    @teacher.update(profile_params)
    @teacher.save

    # Checks if saved correctly. If ok, continues with adding styles. Otherwise redirects to form with validation errors displayed
    if @teacher.save

      # Deletes all associated styles first
      @teacher.styles.delete_all

      # Adds the speciality style to the teacher profile
      add_speciality_style(params[:teacher][:speciality])

      # Checks if the params is exists and if there are multiple other styles first, then adds the styles
      add_other_styles(params[:teacher][:styles])

      flash[:notice] = "Teacher profile edited successfully"

      redirect_to teacher_path(current_user.teacher.id)

    else
      render 'edit'
    end
  end

  # Deletes the current users' Teacher Profile
  def destroy
    @teacher.destroy

    redirect_to teachers_path
  end

  private

  # Finds a Teacher Profile
  def find_profile
    @teacher = Teacher.find(params[:id])
  end

  def profile_params
    params.require(:teacher).permit(:availability, :price, :lesson_length, :bio, :teaching_info, :picture)
  end

  def styles_params
    params.require(:teacher).permit(:speciality, :styles)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  # Loads the student page
  def student_view
  end

  # Loads the teacher page
  def teacher_view
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Guitar Lessons</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# Navbar %>
    <%= render 'shared/navbar' %>

    <%# Flash Messages %>
    <p class="notice alert-success text-center"><%= notice %></p>
    <p class="alert alter-danger text-center"><%= alert %></p>

    <%# Bootstrap Container %>
    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%# NavBar %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# Left-hand side of Navbar %>
  <%= link_to 'Guitar Lessons', teachers_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%# Drop-down menu - Changes depending not logged-in/logged-in/logged-in and has a Teacher Profile %>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">

    <%# Show navbar items when user is logged-in %>
    <% if user_signed_in? %>
      <%= render 'shared/navbar_logged_in' %>

    <%# Show navbar items when user is logged out %>
	  <% else %>
     <%= render 'shared/navbar_guest' %>

    <% end %>
  </div>
</nav>

app/views/shared/_navbar_guest.html.erb
<%# Navbar if no user is logged in %>
<div class="navbar-nav">
  <%= link_to 'Login', new_user_session_path, class: "nav-item nav-link mx-3" %>
</div>
<div class="navbar-nav">
	<%= link_to 'Sign Up', new_user_registration_path, class: "nav-item nav-link mx-3" %>
</div>

app/views/shared/_navbar_logged_in.html.erb
<%# Menu View for anyone with an account and is logged-in %>
<div class="nav-item dropdown pr-sm-5"  >
  <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
    <%= current_user.fullname %>
  </a>
  <%# Main drop-down menu %>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" >
    <%= link_to "Home", teachers_path, class: "dropdown-item" %>
    <%= link_to "Student", student_view_path, class: "dropdown-item" %>

        <%# Changes the menu item depending on whether the user has a Teacher Profile %>
        <% if user_signed_in? && current_user.teacher %>
          <%= link_to "Teacher", teacher_view_path, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Become A Teacher", new_teacher_path, class: "dropdown-item" %>
        <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  </div>
</div>

app/views/teachers/_form.html.erb
<%# Displays any Error Messages %>
<div class="error_messages">
  <% if @teacher.errors.any? %>
    <ul>
      <% @teacher.errors.full_messages.each do |error| %>
        <li class="alert-danger error-flash">*<%= error %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<%# Teacher Profile form %>
<%= form_with model: @teacher, local: true do |form| %>
  <div>
    Speciality: 
      <div>
        <%# Displays all styles as radio buttons. Only one speciality style can be selected per Teacher Profile %>
        <% Style.all.each do |style| %>
          <%= form.radio_button :speciality, style.id, required: true %>
          <%= form.label :speciality, style.name %>
        <% end %> 
      </div>
  </div>
  
  <%# Displays all styles as checkboxes. User can select as many 'other styles' as they want %>
  <div>
    <%= form.label :styles, 'Styles:' %><br>
    <%= form.collection_check_boxes :styles, Style.all, :id, :name, include_hidden: false, acceptance: true do |b| %>
      <div class="form-check form-check-inline">
        <%= b.check_box class: 'form-check-input', acceptance: true %>
        <%= b.label class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :availability, 'Availability:' %><br>
    <%= form.text_field :availability %>
  </div>

  <div>
    <%= form.label :price, 'Price:' %><br>
    <%= form.number_field :price, in: 1..300, step: 1 %>
  </div>

  <div>
    <%= form.label :lesson_length, 'Lesson Length:' %><br>
    <%= form.select(:lesson_length, [['30'], ['60']]) %> mins
  </div>

  <div>
    <%= form.label :bio, 'Bio:' %><br>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :teaching_info, 'Teaching Info:' %><br>
    <%= form.text_area :teaching_info %>
  </div>

  <div>
    <%= form.label :picture, 'Profile Photo: ' %><br>
    <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
  </div>

  <p><div>
    <%= form.submit %>
  </div></p>
<% end %>

app/views/teachers/edit.html.erb
<%# Edit Teacher Profile page %>
<div>
  <div>
    <h2>Edit Teacher Profile</h2>
  </div>
  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/index.html.erb
<div class="row">

    <%# Side bar displaying all Styles %>
    <div class="col-sm-3">
    <h2>Styles</h2>

    <%# Form for filtering profiles by style. All styles are displayed as checkboxes and multiple styles can be selected. %>
    <div class="form-check">
    <%= form_with model: @style, url: teachers_path, method: :get, class: "form-check", local: true do |form| %>
      <div>
        <%= form.collection_check_boxes :name, Style.all, :id, :name %>
      </div>
      <div>
        <%= form.submit "Filter Styles" %> 
      </div>
      <% end %>
    </div>
  </div>

    <%# Main area displaying all teacher profiles %>
    <div class="col-sm-9">

      <%# Teacher Profile cards. Lists all profiles currently in the database %>
      <% @teachers.each do |teacher| %>

      <div class="card mb-3">
        <div class="row no-gutters">
        
          <div class="col-md-4">
            <%= image_tag teacher.picture, class: "img-fluid" if teacher.picture.attached? %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h4 class="card-title"><%= link_to teacher.user.fullname, teacher_path(teacher) %></h4><br>
                  <%# Displays the profiles speciality style %>
                  <% teacher.teachers_styles.each do |style| %> 
                    <% if style.speciality == true %>
                      <b>Speciality:</b> <%= style.style.name %><br>
                    <% end %>
                  <% end %>
                  <%# Displays the profiles other styles %>
                  <b>Other Styles:</b>
                  <% teacher.teachers_styles.each do |style| %> 

                    <% if style.speciality == false %>
                      <%= style.style.name %>, 
                    <% end %>

                  <% end %><br>
                  <b>Availability:</b> <%= teacher.availability %><br>
                  <b>Bio:</b> <%= teacher.bio %>
                </p>
            </div>
          </div>
        </div>
      </div>
        <% end %>
    </div>
</div>

app/views/teachers/new.html.erb
<%# Form page for a new Teacher Profile %>
<div>
  <div>
    <h2>Create Teacher Profile</h2>
  </div>
  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/show.html.erb
<%# A single Teacher Profile listing %>
<div class="row no gutters">
  <%# Profile Photo %>
  <div class="col-sm-4">
    <%= image_tag @teacher.picture, class: "img-fluid" if @teacher.picture.attached? %>
  </div>

  <%# All Profile Info %>
  <div class="col-sm-8">

    <%# Specialities %>
    <h2><%= @teacher.user.fullname %></h2>
    <% @teacher.teachers_styles.each do |style| %> 
      <% if style.speciality == true %>
        <b>Speciality:</b> <%= style.style.name %><br>
      <% end %>
    <% end %>

    <%# Other Styles %>
    <b>Other Styles:</b>
    <% @teacher.teachers_styles.each do |style| %> 
      <% if style.speciality == false %>
        <%= style.style.name %>, 
      <% end %>
    <% end %><br>
    <%# Other small information %>
    <b>Availability:</b> <%= @teacher.availability %><br>
    <b>Price:</b> $<%= @teacher.price %><br>
    <b>Lesson Length:</b> <%= @teacher.lesson_length %> mins
    <br>
    <%# Purchase Lesson button: Only to be shown if a user is signed in %>
    <% if user_signed_in? %>

      <%# Link to Stripe for payment %>
      <button type="button" class="btn btn-success"><%= link_to 'Purchase A Lesson', "", id: "stripe" %></button>
      

    <% else %>
      <p>(User must have an account and be logged-in to purchase a lesson)</p>
    <% end %>
  </div>
</div>

<%# Bulky Info %>
<div class="row">
  <div class="col-sm-12">
    <h5>Biography:</h5>
    <p><%= @teacher.bio %></p>
    <h5>Teaching Info:</h5>
    <p><%= @teacher.teaching_info %></p>
  </div>
</div>

<div>
  <%= link_to 'Back', teachers_path %>
</div>

<%= javascript_pack_tag "stripe" %>

app/views/users/student_view.html.erb
<%# View when user selects 'Student' from drop-down menu %>
<div>

  <%# Displays current user details %>
  <div>
    <h1><%= current_user.fullname %></h1>
    <h6><%= current_user.email  %></h6>
  </div>
  <hr>
  <div>
    <div>
      <h2>Paid Lessons</h2>
      <hr>
    </div>

    <%# Displays all Bookings current user has as a Student %>
    <div>
      <% current_user.bookings.each do |booking| %>
        <p>
          <b>Name: </b> <%= booking.teacher.user.fullname %><br>
          <b>Email: </b> <%= booking.teacher.user.email %><br>
          <b>Price: </b>$<%= booking.teacher.price %><br>
          <b>Lesson Length: </b><%= booking.teacher.lesson_length %> mins<br>
          <hr>
        </p>
      <% end %>
    </div>
</div>

app/views/users/teacher_view.html.erb
<%# View when user selects 'Teacher' from drop-down menu %>
<div class="row">
  <%# Side Links %>
  <div class="col-sm-3">
    <div>
      <%= link_to 'View Profile', teacher_path(current_user.teacher.id) %><br>
      <%= link_to 'Edit Profile', edit_teacher_path(current_user.teacher.id) %><br>
      <%= link_to 'Delete Profile', teacher_path(current_user.teacher.id), method: :delete, data: { confirm: "Are you sure you want to delete your Teacher Profile?" } %>
    </div>
  </div>
  <%# Main Section %>
  <div class="col-sm-9">
    <div>
      <h1><%= current_user.fullname %></h1>
      <h6><%= current_user.email  %></h6>
    </div>
    <hr>
    <div>
      <div>
        <h2>Upcoming Teacher Lessons</h2>
        <hr>
      </div>

      <%# All guitar lessons User has as a Teacher %>
      <div>
        <% current_user.teacher.bookings.each do |booking| %>
          <p>
            <b>Name: </b> <%= booking.user.fullname %><br>
            <b>Email: </b> <%= booking.user.email %><br>
            <b>Price: </b>$<%= booking.teacher.price %><br>
            <b>Lesson Length: </b><%= booking.teacher.lesson_length %> mins<br>
            <hr>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>